export const UPDATE_MODE_DAFAULT = "UPDATE_MODE_DAFAULT";
export const UPDATE_MODE_CHANGE_PASSWORD = "UPDATE_MODE_CHANGE_PASSWORD";
export const UPDATE_MODE_EDIT_PROFILE = "UPDATE_MODE_EDIT_PROFILE";

